// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $post_id_ from "./routes/post/[id].tsx";
import * as $post_layout from "./routes/post/_layout.tsx";
import * as $post_add from "./routes/post/add.tsx";
import * as $post_index from "./routes/post/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/post/[id].tsx": $post_id_,
    "./routes/post/_layout.tsx": $post_layout,
    "./routes/post/add.tsx": $post_add,
    "./routes/post/index.tsx": $post_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
